name: Maven Build on Self-Hosted Runner

on: push
  
jobs:
  build:
    name: Build with Maven-tools-
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn clean install
